name: test
on: [push, pull_request]
jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.10', 3.11]
    steps:
    - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4
    - name: test
      run: |
        sudo apt-get update && sudo apt-get install python3-dev && \
        sudo pip3 install -U -r test-requirements.txt -r requirements.txt -r test-requirements.txt && \
        PYTHONPATH=. pytype . && \
        PYTHONPATH=. pytest
